services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      #      mac: start
      #      - ASPNETCORE_Kestrel__Certificates__Default__Password=pass
      #      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      #      mac: end
      - Kestrel__EndPoints__WebApi__Protocols=Http1
      - Kestrel__EndPoints__WebApi__Url=http://+:8080
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=password;Include Error Detail=true
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      #      Linux
      #      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      #      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      #      Mac
      - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
  
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      #      mac: start
      #      - ASPNETCORE_Kestrel__Certificates__Default__Password=pass
      #      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      #      mac: end
      - Kestrel__EndPoints__WebApi__Protocols=Http1
      - Kestrel__EndPoints__WebApi__Url=http://+:8080
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=password;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=http://discount.grpc:8080
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      #      Linux
      #      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      #      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      #      Mac
      - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
  
  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Kestrel__Endpoints__Grpc__Url=http://0.0.0.0:8080
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - ConnectionStrings__Database=Data Source=/app/db/DiscountDb.db
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
      - discountdb_data:/app/db
  
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
  
  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=BasketDb
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - postgres_basket:/var/lib/postgresql/data
  
  distributedcache:
    container_name: distributedcache
    restart: unless-stopped
    ports:
      - "6379:6379"